### ISSUE TITLE
Import problem in v0.14.0: No module named 'sympde.utilities'

### ISSUE THREAD

**Issue by spossann** [pyccel/sympde#105]
Using sympde 0.14.0 I get the following error (absent in version 0.13.1):

struphy/geometry/domain_3d.py:20: in <module>                                                                                                                                                
    from sympde.topology import Mapping                                                                                                                                                      
env/lib/python3.8/site-packages/sympde/__init__.py:3: in <module>                                                                                                                            
    from .topology  import *                                                                                                                                                                 
env/lib/python3.8/site-packages/sympde/topology/__init__.py:9: in <module>                                                                                                                   
    from .callable_mapping   import *                                                                                                                                                        
env/lib/python3.8/site-packages/sympde/topology/callable_mapping.py:1: in <module>                                                                                                           
    from sympde.utilities.utils import lambdify_sympde                                                                                                                                       
E   ModuleNotFoundError: No module named 'sympde.utilities'

**Comment by anlavandier** [comment]
PR #104 should fix this. I am waiting for @yguclu to review and merge the PR.

**Comment by anlavandier** [comment]
Fixed by #104. Version 0.14.1 is on `pypi` doesn't not have this issue.
