### ISSUE TITLE
Add information about relative orientation to 3D connectivity

### ISSUE THREAD

**Issue by yguclu** [pyccel/sympde#115]
The information that is currently stored in the `connectivity` dictionary of a multi-patch domain is not sufficient to describe the relative orientation of two cuboid patches sharing a given interface. This additional information should be included.

**Comment by saidctb** [comment]
In 3D, we need 3 integers to cover all the possibilities, see reference https://www.sintef.no/globalassets/upload/ikt/9011/geometri/isogeometric-analysis_focus_3d_conference.pdf

**Comment by yguclu** [comment]
@saidctb Can we close this issue after PR #130?
