### ISSUE TITLE
Consider updating sympy dependencies

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/sympde#124]
Currently sympde pins sympy to sympy<1.7,>=1.2, while the latest sympy version is 1.11.1. This means that anyone who wants to keep a working installation of sympde cannot use any of the improvements made to sympy in the last 2.5 years. Furthermore this version of sympy relies on packages which are gradually becoming out of date.

For example, using sympy version 1.6.2 on python 3.10 results in the following warning when using Pyccel:
```
../../../../.local/lib/python3.10/site-packages/sympy/external/importtools.py:4
  /home/scitas/.local/lib/python3.10/site-packages/sympy/external/importtools.py:4: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils.version import LooseVersion
```
Presumably when Python 3.12 becomes available (around October), it will be impossible to run Pyccel with this version while preserving a working installation of sympde.

As a result I think it would be worth looking into how to update the sympy dependency

**Comment by EmilyBourne** [comment]
Ah yes you're right, sorry. Do you want me to turn the information about Python 3.12 into a comment on that issue?

**Comment by yguclu** [comment]
Yes please!
