### ISSUE TITLE
Laplace(1) should be evaluated as 0

### ISSUE THREAD

**Issue by yguclu** [pyccel/sympde#31]
Every differential operator applied to a number or a constant should return zero.

**Comment by yguclu** [comment]
Every differential operator applied to a number or a constant should return zero.

**Comment by saidctb** [comment]
the evaluation happens only after calling `TerminalExpr`  and it gives the right answer

**Comment by ratnania** [comment]
@saidctb  it depends. There are some rules that should be implemented by every differential operator. And their behavior w.r.t constants and numbers is one of them
