### ISSUE TITLE
`Domain.from_file` not storing strings correctly

### ISSUE THREAD

**Issue by ratnania** [pyccel/sympde#43]
when reading a geometry from a file, the boundary names are not `r"\Gamma_1"` etc

**Comment by yguclu** [comment]
@saidctb Do we still have this problem?

**Comment by saidctb** [comment]
> @saidctb Do we still have this problem?

we don't use the boundary name to create the boundary, we use the patch name, the axis, and the extremity 
so I didn't face any problem with the boundary name

**Comment by yguclu** [comment]
Can we close this issue then?

**Comment by saidctb** [comment]
for me, yes
